export const STATUTORY_PERMISSIONS = {
  STATUTORY_CONFIG_READ: 'STATUTORY_CONFIG_READ',
  STATUTORY_CONFIG_WRITE: 'STATUTORY_CONFIG_WRITE',
  STATUTORY_CONFIG_APPROVE: 'STATUTORY_CONFIG_APPROVE',
  COMPLIANCE_PERIOD_READ: 'COMPLIANCE_PERIOD_READ',
  COMPLIANCE_PERIOD_WRITE: 'COMPLIANCE_PERIOD_WRITE',
  COMPLIANCE_EXCEPTION_READ: 'COMPLIANCE_EXCEPTION_READ',
  COMPLIANCE_EXCEPTION_RESOLVE: 'COMPLIANCE_EXCEPTION_RESOLVE',
  COMPLIANCE_DOCUMENT_READ: 'COMPLIANCE_DOCUMENT_READ',
};